# Generated by Django 3.0.4 on 2020-03-31 07:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100, null=True)),
                ('city', models.CharField(max_length=30, null=True)),
                ('state', models.CharField(max_length=30, null=True)),
                ('event_date', models.DateField(blank=True, null=True)),
                ('budget', models.CharField(max_length=30, null=True)),
                ('event_type', models.CharField(max_length=30, null=True)),
                ('Sound_system', models.CharField(max_length=30, null=True)),
                ('Catering', models.CharField(max_length=30, null=True)),
                ('Projector', models.CharField(max_length=30, null=True)),
                ('Decoration', models.CharField(max_length=30, null=True)),
                ('Photographer', models.CharField(max_length=30, null=True)),
                ('register_date', models.DateField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Event Portal',
            },
        ),
    ]
