# Generated by Django 3.0.4 on 2020-04-01 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20200331_2312'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'verbose_name_plural': 'FeedBack'},
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='comment',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
