# Generated by Django 3.0.4 on 2020-04-02 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('events', '0011_auto_20200401_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='manager_profile_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manager_profile', to='accounts.Profile'),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='Catering',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no'), ('need_to_work', 'NEED TO WORK'), ('in_process', ' IN PROCESS'), ('done', 'DONE')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='Decoration',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no'), ('need_to_work', 'NEED TO WORK'), ('in_process', ' IN PROCESS'), ('done', 'DONE')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='Photographer',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no'), ('need_to_work', 'NEED TO WORK'), ('in_process', ' IN PROCESS'), ('done', 'DONE')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='Projector',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no'), ('need_to_work', 'NEED TO WORK'), ('in_process', ' IN PROCESS'), ('done', 'DONE')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='Sound_system',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no'), ('need_to_work', 'NEED TO WORK'), ('in_process', ' IN PROCESS'), ('done', 'DONE')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='confirmation',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='profile_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to='accounts.Profile'),
        ),
    ]
