# Generated by Django 3.0.4 on 2020-04-02 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_auto_20200402_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='confirmation_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
