# Generated by Django 3.0.4 on 2020-04-02 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_eventregistration_confirmation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventregistration',
            name='confirmation',
            field=models.CharField(choices=[('accepted', 'accepted'), ('pending', 'pending'), ('reject', 'reject')], max_length=30, null=True),
        ),
    ]
