# Generated by Django 3.0.4 on 2020-04-02 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_auto_20200402_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventregistration',
            name='Catering',
            field=models.CharField(choices=[('pending', 'pending'), ('need_to_work', 'NEED TO WORK'), ('in_process', ' IN PROCESS'), ('done', 'DONE')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='Decoration',
            field=models.CharField(choices=[('pending', 'pending'), ('need_to_work', 'NEED TO WORK'), ('in_process', ' IN PROCESS'), ('done', 'DONE')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='Photographer',
            field=models.CharField(choices=[('pending', 'pending'), ('need_to_work', 'NEED TO WORK'), ('in_process', ' IN PROCESS'), ('done', 'DONE')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='Projector',
            field=models.CharField(choices=[('pending', 'pending'), ('need_to_work', 'NEED TO WORK'), ('in_process', ' IN PROCESS'), ('done', 'DONE')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='Sound_system',
            field=models.CharField(choices=[('pending', 'pending'), ('need_to_work', 'NEED TO WORK'), ('in_process', ' IN PROCESS'), ('done', 'DONE')], max_length=30, null=True),
        ),
    ]
